# Generated by Django 3.2.14 on 2023-01-02 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='user_name',
            field=models.CharField(blank=True, default='user', max_length=15, null=True, verbose_name='Фойдаланувчи номи'),
        ),
    ]
