# Generated by Django 4.1.4 on 2022-12-21 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=512, verbose_name='Имя')),
                ('second_name', models.CharField(max_length=512, verbose_name='Фамилия')),
                ('third_name', models.CharField(max_length=255, verbose_name='Отчество')),
                ('phone', models.CharField(max_length=255, verbose_name='Номер телефона')),
                ('sector', models.IntegerField(choices=[(1, 'первый'), (2, 'второй'), (3, 'третий'), (4, 'четвертый')], verbose_name='Сектор')),
            ],
            options={
                'verbose_name': 'Исполнитель',
                'verbose_name_plural': 'Исполнители',
                'db_table': 'task_users',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_taken', models.DateField(verbose_name='Дата принятия задачи')),
                ('time_started', models.DateTimeField(auto_now=True, verbose_name='Дата создания задачи')),
                ('time_finished', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата закрытия задачи')),
                ('time_of_day', models.CharField(choices=[('09:00-10:00', '09:00-10:00'), ('10:00-11:00', '10:00-11:00'), ('11:00-12:30', '11:00-12:30'), ('14:00-15:30', '14:00-15:30'), ('16:00-17:00', '16:00-17:00'), ('17:00-18:00', '17:00-18:00')], max_length=255, verbose_name='Время исполнение')),
                ('name_of_task', models.TextField()),
                ('status', models.BooleanField(default=False)),
                ('executor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_app.executormodel')),
            ],
            options={
                'verbose_name': 'Задач',
                'verbose_name_plural': 'Задачи',
                'db_table': 'task_model',
                'managed': True,
            },
        ),
    ]
