# Generated by Django 4.1.4 on 2022-12-21 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='confirmation',
            field=models.FileField(blank=True, null=True, upload_to='executor_conf/'),
        ),
    ]
