# Generated by Django 3.2.14 on 2023-01-02 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLogModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_name', models.TextField(blank=True, null=True)),
                ('error_time', models.DateTimeField()),
                ('error_of_task', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='status_exist',
            field=models.BooleanField(default=False),
        ),
    ]
